### ISSUE TITLE
Fill row / fill to right not working in safari

### ISSUE THREAD

**Issue by slfhstr** [simonwep/ocular#49]
### Support guidelines

- [X] I've read the [FAQs](https://github.com/simonwep/ocular-docker?tab=readme-ov-file#faq)

### Description

The `fill row` and `fill right` does not work in my browser Safari

### Environment

- Browser : Safari 17.5
- OS : Mac Monterey 12.7.5
- Docker compose release 1.2 (image 1.4)

### Expected behaviour

Data flow into columns as expected

**Comment by slfhstr** [comment]
I did later try firefox and had the same problem.
Maybe it's my browser settings (JS disabled ?) or something.

**Comment by simonwep** [comment]
Nah, I always forget about other browser when working on a personal project - bad habit of mine haha :D Should be easy to fix, I allocated some time this weekend to take a look at all the new things that came up in this repo, it's been a few tough weeks for me hence the longe period of zero contributions haha
