### ISSUE TITLE
When switching to a (new) different year, all the categories get reset

### ISSUE THREAD

**Issue by Hoverth** [simonwep/ocular#58]
### I've found a bug and checked that ...

- [X] ...there are no open or closed issues that are related to my problem
- [ ] ...it's definitely a bug and not a feature request

### Description

I'm unsure if this is a bug, or just a feature. Either way, I think this would improve ease-of-use for ocular in a meaningful way.

### Environment

Ocular v1.6.0 (103a494, Sun Oct 27 2024) run off docker-compose.

### Expected behaviour

All the categories from the previously selected year get added to the new year, or the new year starts with all the default categories.

### Steps to reproduce

Switch to a different year than the default, with the current year having non-default categories (I don't know if this makes a difference).

**Comment by simonwep** [comment]
I merged you PR, thanks again! :)
