### ISSUE TITLE
Highlight currently focused row in income and expense tabs

### ISSUE THREAD

**Issue by kyearb** [simonwep/ocular#62]
### Support guidelines

- [X] My request extends the functionality of Ocular in a meaningful way.
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been requested before.

### Description

The current month already gets highlighted and a frozen month row is only the way. In addition to this row highlighting would make it easier to tell what row you are on. The alternating colours help a lot already, but since the leftmost column doesn't use alternating colours it's still not easy to tell what row you are on at first glance.

### Solution

Add row highlighting. This can either be done by highlighting the row that the cursor is on or by highlighting the row that the mouse is hovering over.

**Comment by simonwep** [comment]
Great idea, but I'm not sure about the execution, I played around with different styles but adding another shade seems to be overkill and I'm not that sure about the solution I've came up with so far:

<img width="217" alt="image" src="https://github.com/user-attachments/assets/4d132a10-4628-4856-921d-d3978306ec90" />

<img width="183" alt="image" src="https://github.com/user-attachments/assets/f1d80488-d854-40ab-ae65-2e7599159c66" />

One Idea I liked was highlighting the box like google sheets does (and they must have a reason to have come up with that haha)

<img width="152" alt="image" src="https://github.com/user-attachments/assets/6174d9b5-41ab-4ac6-9995-abbb90330ec0" />


what do you think?

**Comment by kyearb** [comment]
I like how it's done on google sheets as well. I don't see the highlighting in the screenshot you took though. Is the intent to highlight the month and item name as well?

**Comment by simonwep** [comment]
Yeah for the first two screenshots it's difficult to see. That was my problem as well, but I'd then do it as google sheets does including highlighting the name :)
